### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by no-ods** [MCmodding4K/SkillClient#153]
yo, i was wondering if i could get some help. whenever i click to turn on kill aura or any other hack, it always crashes afterwards.

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: joptsimple.internal.Strings.join(Ljava/lang/Iterable;Ljava/lang/String;)Ljava/lang/String;

^^ dunno if that will help, but i added it anyways.
thank youuu

**Comment by MCmodding4K** [comment]
Fixed in latest release
