### ISSUE TITLE
SkillClient 1.12.X Keybindings

### ISSUE THREAD

**Issue by Dark-God123** [MCmodding4K/SkillClient#160]
Every time I bind something, as soon as I close Minecraft, the config resets the keybinds and I have to rebind them. I have the config with everything the way I want it, and when I try to replace the reset one, it resets it all over again. When I used the 1.11.X version, the config didn't reset the keybinds.  Why is this happening? And can this be fixed?

**Comment by MCmodding4K** [comment]
Thats due to forge, its going to be fixed in next release
