### ISSUE TITLE
Settings not persisting between startup/shutdown

### ISSUE THREAD

**Issue by MatthewOverall** [MCmodding4K/SkillClient#165]
The config file keeps clearing on startup resulting in existing settings being wiped out. 
Also, loading settings from disk using `.settings load <configname>` does not work.

**Comment by lastbowman** [comment]
Same , could it be because it is only looking for the default .mine craft folders , may need to also be able to check the folder path force curse / twitch launcher or multi mc's folder pathing

**Comment by GlitchHead** [comment]
Already addressed in #160 I really hope the next release is soon because I have to spend a few minutes changing the settings on client start.

**Comment by MCmodding4K** [comment]
fixed in latest version
