### ISSUE TITLE
Kill Aura crashes the game?

### ISSUE THREAD

**Issue by Timtee** [MCmodding4K/SkillClient#174]
Originally i thought it was journey map doing this, but apparently, If i open the kill aura tab in the settings page for the mod, It crashes the game entirely.

[crash-2018-04-13_01.25.31-client.txt](https://github.com/MCmodding4K/SkillClient/files/1906075/crash-2018-04-13_01.25.31-client.txt)

This is the crash log, you can see it didn't take long at all to crash the game. But do you know why the Kill Aura kills the game if you open the menu for it?

**Comment by MCmodding4K** [comment]
going to be fixed in next release
