### ISSUE TITLE
Disable menu movement keys doesn't actually work

### ISSUE THREAD

**Issue by wyrdo** [MCmodding4K/SkillClient#175]
I would like to disable UP/DOWN/LEFT/RIGHT menu navigation since I use those to move myself around (instead of WASD).  But even when they're supposed to be disabled, they're not.  Even if the GUI is off, they still activate and deactivate cheats.

**Comment by MCmodding4K** [comment]
there is an option called " Use arrow-keys to navigate" in HUD
