### ISSUE TITLE
Safe FreeCam

### ISSUE THREAD

**Issue by rafamariofan** [MCmodding4K/SkillClient#180]
This client is the best Free Forge Based client that I've ever seen. It's really helping me to survive in a server like 2b2t

However, I'm getting kicked by AAC for using FreeCam. 

Can you add a Safe Freecam mode that isn't treated like flight?

Thanks a lot for your mod.

**Comment by MCmodding4K** [comment]
oh, there was a bug in freecam, i am sorry!
Fixed in b10.6
