### ISSUE TITLE
Custom tab (Player heads) glitch/bug - 1.12.2 Forge

### ISSUE THREAD

**Issue by ThatOneJose95** [MCmodding4K/SkillClient#184]
Hello! I use the 1.12 version of Skillclient for Forge, and it works amazing. The thing is one of the custom tabs (Player heads) haves a glitch where the search bar is glitched and I can't manage to write, and   ##my MC lags a lot while scrolling nad loading heads so I can't find anything.

**Comment by MCmodding4K** [comment]
yeah, forge f*cked up in 1.12
https://gitlab.com/mcmodding4k/SkillClient
