### ISSUE TITLE
Crashes Upon Start Up [1.12.2]

### ISSUE THREAD

**Issue by princessbinas** [MCmodding4K/SkillClient#186]
SkillClient Version:  skillclient-1.12.2-b11.5

I used SkillClient long ago, back before it was bundled with Forge. Recently, I tried installing it in numerous ways. The way on the current download page on the SkillClient site and the old way where it was its own version. In both the current way, and old way, I am unable to get past the main menu without it freezing and being forced to exit out of the game. I am unable to generate crash reports for some reason, so the best I can provide is the latest log file from the logs folder.

Log File: [latest.log](https://github.com/MCmodding4K/SkillClient/files/2199851/latest.log)

**Comment by MCmodding4K** [comment]
copy the report from the folder "crash-reports". Also try

**Comment by princessbinas** [comment]
I was using 1.12.2.

**Comment by MCmodding4K** [comment]
can't help you without any log
