### ISSUE TITLE
client not launching

### ISSUE THREAD

**Issue by ShownPC** [MCmodding4K/SkillClient#38]
when i try to launch the client it shows a white screen and spams the console with
ERROR tk.skillclient.ej - ########## GL ERROR ##########
ERROR tk.skillclient.ej - @ Post render
ERROR tk.skillclient.ej - 1282: Invalid operation
it seems that the client still works i just cant see anything, whenever i click stuff i hear the button press sound and in some cases it opens pages on my browser.

**Comment by MCmodding4K** [comment]
try to launch normal 1.11 and then again skillclient
does it work now?

**Comment by ShownPC** [comment]
I already tried that, it doesn't. I also tried messing with drivers, and gave the client to a friend and he had the same problem.
while trying it again, i accidentally maximized the client and it fixed it..... sorry for wasting your time

**Comment by MCmodding4K** [comment]
I found a solution, fastrender:off or wait for b4.0 (soon, maybe in few hours)
