### ISSUE TITLE
How to use colored letters without being disconnected from the server

### ISSUE THREAD

**Issue by Slender35** [MCmodding4K/SkillClient#46]
![capturar](https://cloud.githubusercontent.com/assets/17165016/21426598/efc93ca0-c836-11e6-9ccc-c110692f3df8.PNG)

I've tried using this shift + 3 more n leaves nothing what should I do the whole time having colorful character appears illegal talk

**Comment by MCmodding4K** [comment]
Yes, I know it often does not work in chat, but sometimes with specific Plugins on Servers or in Books, Anvil etc
