### ISSUE TITLE
help with nbt tag and cmd. give

### ISSUE THREAD

**Issue by Slender35** [MCmodding4K/SkillClient#47]
what you can do with the nbt tags? can you put particles in items using cmd. give? could you pass me all the nbt tags pf I know all and researched more always are separated, one more question how to modify blocks type armor stand put her and she turns to another type block sand?. thanks have a nice day

**Comment by MCmodding4K** [comment]
it works like /give
You should just look up for the /give command, but format like /give stone 1 0 {...}
