### ISSUE TITLE
Issues834

### ISSUE THREAD

**Issue by Thrywyn** [MCmodding4K/SkillClient#57]
Inhalt/Content:  Hi, i cannot change entity targets on KillAura, when i do it crashes.

Log:
---- Minecraft Crash Report ----
// Sorry :(

Time: 1/8/17 4:04 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at tk.skillclient.ua.SkillClient(Unknown Source)
	at tk.skillclient.tZ.SkillClient(Unknown Source)
	at tk.skillclient.tZ.SkillClient(Unknown Source)
	at tk.skillclient.dV.goto(Unknown Source)
	at tk.skillclient.dV.short(Unknown Source)
	at tk.skillclient.dV.SkillClient(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	SkillClient Version: Minecraft 1.11 | SkillClient b4.3
	Minecraft Version: 1.11
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177785400 bytes (169 MB) / 453939200 bytes (432 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: SkillClient1.11
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.11-rv2.zip, CodeCrafted Custom .zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.11_HD_U_B2
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.09
	OpenGlRenderer: GeForce GTX 770/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MCmodding4K** [comment]
try the new gui

**Comment by MCmodding4K** [comment]
and update to newest version
