### ISSUE TITLE
Issues316

### ISSUE THREAD

**Issue by dafael555** [MCmodding4K/SkillClient#65]
Heya,
My name is Rafael, and I've had some problems with the SkillClient.
At first when trying it out it worked fine, but now I cannot access singleplayer or multiplayer worlds.
I tried turning my wifi off and back on, and also tried a normal version of minecraft to check if it had anything to do with the launcher itself. The normal version worked fine.
All the multiplayer servers cannot connect and when I try to open a singleplayer world, it says ''0%'' on the screen, and stays stuck that way.
Could you help me with this?
Greetings,
Rafael

**Comment by MCmodding4K** [comment]
disable blink xD Will be fixed soon.
