### ISSUE TITLE
Client suggestions "Devin"

### ISSUE THREAD

**Issue by devinHACKER** [MCmodding4K/SkillClient#69]
My skillclient suggestion:

Mass tpahere (send /tpahere name ) to everyone in the server    + antikickcooldown  (same cooldown as spammer)

Mass msg (send msg name and text) to everyone in the server   +antikickcooldown  (same cooldown as spammer)

These will help when you hack a server.

Mass delete warp (send /delwarp warp name)  removes all warps  +antikickcooldown  (same cooldown as spammer)

Mass ban (send /ban name) to everyone in the server  +antikickcooldown (same cooldown as spammer) and add a list of people not to ban

Mass kick (send /kick name) to everyone in the server  +antikickcooldown (same cooldown as spammer) and add a list of people not to kick

Add a good phase hack :D

Extra: https://youtu.be/Xksant_CgaM and maybe ive this dupe glitch is true maybe you can recreate it 😄

**Comment by MCmodding4K** [comment]
so basicly send command with the name of everyone
