### ISSUE TITLE
Madrid

### ISSUE THREAD

**Issue by MCmodding4K** [MCmodding4K/SkillClient#73]
More commands, such as: 
* .t (to disable mods, and enable them)
* .addlore <Lore> (Adds a lore to the item, Creative Mode only.)
* .prefix <Prefix> (Sets the prefix to something else, let's say instead of "." we can use "#")
* .taco (A little taco on our hotbar, this is not necessary, I just like tacos, lol.)
* .addalt <Player Name> (Adds a player to the alt list in game)
* .potion add/remove <Effect> <Amplifier> <Duration> (Adds/Removes an effect to a water bottle, or a potion, Creative Mode only.)
* .author <Author> (Sets the author of a book to anyone, Creative Mode only)
I have loads more commands, this is just some.

 New Mods 
* Mass TPA (TPA's to everyone on the server and stops when someone accepts) (We can set our own duration between commands)
* Mass MSG (MSG's everyone on the server a certain message and stops when message is delievered to all members) (We can set our own duration between commands)
* Mass TPAHere (TPAHere's everyone on the server and stops when someone accepts) (We can set our own duration between commands)
* A working BookHack, which executes a command when player clicks the link.
* Bypasses for Mineplex, Hypixel, MineHeroes in Fly, Speed, and others.
* AntiKillAuraBan (Which basically ignores all the bots around and only focuses on player, you know when an AntiCheat puts players around you so they check if you have KillAura, and you hit those fake players and get banned, well I've seen a lot of hack clients that can bypass that, such as Impact, so go ahead!)
I've got loads more, contact me if you want more! Thanks!(bearbeitet)

**Comment by Xiione** [comment]
It'd be great if you could fix the .give command for custom items and such.

**Comment by MCmodding4K** [comment]
still not fixed?
1.8 or 1.11 and version pls :)

**Comment by Xiione** [comment]
I'm not sure what you mean. Are you asking for the versions of the client I am using? If so, I tried both the 1.8 and 1.10 - 1.11.2 versions of Skillclient b6.2.

**Comment by MCmodding4K** [comment]
.book author 
.rename
added
