### ISSUE TITLE
SkillClient cant run

### ISSUE THREAD

**Issue by Palpalich** [MCmodding4K/SkillClient#78]
When i run skillclient1.11 it cant run, thrers some llines from console

**Comment by Palpalich** [comment]
[Launcher] Starting Minecraft SkillClient1.11...
[Launcher] Launching in: D:\Games\MC\.minecraft
[Launcher] Processing post-launch actions. Assist launch: true
===============================================================================================
> Exception in thread "Client thread" java.lang.NumberFormatException: Illegal embedded sign character
> 	at java.math.BigInteger.<init>(Unknown Source)
> 	at com.skillclient.w.<init>(Unknown Source)
> 	at com.skillclient.iU.SkillClient(Unknown Source)
> 	at com.skillclient.iU.<init>(Unknown Source)
> 	at net.minecraft.client.main.Main.main(Unknown Source)
> Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Here I am!

**Comment by MCmodding4K** [comment]
thats due to tlauncher, will be fixed in next release

**Comment by Palpalich** [comment]
what launcher i must use to run any client without errors?

**Comment by MCmodding4K** [comment]
any other

**Comment by Palpalich** [comment]
can u recomend me something?

**Comment by Palpalich** [comment]
mrlauncher and mllauncher make same error

**Comment by MCmodding4K** [comment]
default?
